# backend:
#   name: github
#   repo: snamyorg1/test1
#   base_url: https://suresh-issue-82.dcycleproject.org
#   auth_endpoint: /auth/github/repo/69b6cfce3d9141c0c4f7792a
# media_folder: static/uploads
# public_folder: /uploads
# collections:
#   - name: blog
#     label: Blog
#     folder: content/blog
#     create: true
#     slug: '{{slug}}'
#     fields:
#       - label: Title
#         name: title
#         widget: string
#       - label: Date
#         name: date
#         widget: datetime
#       - label: Body
#         name: body
#         widget: markdown
#   - name: "awards"
#     label: "Awards"
#     files:
#       - file: "docs/_data/awards.yml"
#         label: "Awards List"
#         name: "awards_list"
#         fields:
#           - label: "Awards"
#             name: ""
#             widget: "list"
#             fields:
#               - label: "Name"
#                 name: "name"
#                 widget: "object"
#                 fields:
#                   - { label: "English", name: "en", widget: "string" }
#                   - { label: "French", name: "fr", widget: "string" }

#               - label: "Media"
#                 name: "media"
#                 widget: "object"
#                 fields:
#                   - { label: "Image", name: "path", widget: "image" }

#                   - label: "Alt Text"
#                     name: "alt"
#                     widget: "object"
#                     fields:
#                       - { label: "English", name: "en", widget: "string" }
#                       - { label: "French", name: "fr", widget: "string" }

locale: 'fr'
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

backend:
  name: github
  repo: snamyorg1/test1
  base_url: https://suresh-issue-82.dcycleproject.org
  auth_endpoint: /auth/github/repo/69b6cfce3d9141c0c4f7792a

media_folder: "docs/media"
public_folder: "/media"

collections:
  # - name: 'articles'
  #   create: true
  #   label: 'Articles'
  #   folder: 'docs/_articles/_posts/'
  #   slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
  #   # I'd like the summary to show the date, but I can't because of
  #   # https://github.com/decaporg/decap-cms/issues/7753
  #   # This does not work:
  #   # summary: '{{year}}-{{month}}-{{day}} - {{title}}'
  #   summary: '{{title}}'
  #   fields:
  #     - label: 'Titre en français'
  #       name: 'title'
  #       widget: 'string'
  #     - label: 'Titre en anglais'
  #       name: 'title_en'
  #       widget: 'string'
  #       required: false
  #     - label: 'Contenu en français'
  #       name: 'body'
  #       widget: 'markdown'
  #       required: false
  #     - label: 'Contenu en anglais'
  #       name: 'body_en'
  #       widget: 'markdown'
  #       required: false
  #     - label: 'Documents en français'
  #       name: 'documents'
  #       widget: 'list'
  #       required: false
  #       field: {label: Document, name: document, widget: file, required: false}
  #     - label: 'Documents en anglais'
  #       name: 'documents_en'
  #       widget: 'list'
  #       required: false
  #       field: {label: Document, name: document, widget: file, required: false}
  #     - label: 'Redirects en français'
  #       description: "Ajouter des redirections pour les anciennes URL de cet article. Par exemple: /fr/ancien-article"
  #       name: 'redirects'
  #       widget: 'list'
  #       required: false
  #       field: {label: Redirect, name: redirect, widget: string, required: false}
  #     - label: 'Redirects en anglais'
  #       description: "Ajouter des redirections pour les anciennes URL de cet article. Par exemple: /en/old-article"
  #       name: 'redirects_en'
  #       widget: 'list'
  #       required: false
  #       field: {label: Redirect, name: redirect, widget: string, required: false}
  # - name: 'projects'
  #   create: true
  #   label: 'Projets'
  #   folder: 'docs/_projects/_posts/'
  #   slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
  #   summary: '{{projectyear}} {{title}}'
  #   fields:
  #     - label: 'Titre en français'
  #       name: 'title'
  #       widget: 'string'
  #     - label: 'Titre en anglais'
  #       name: 'title_en'
  #       widget: 'string'
  #       required: false
  #     - label: 'Année'
  #       name: 'projectyear'
  #       widget: 'string'
  #       required: false
  #     - label: 'Image'
  #       name: 'image'
  #       widget: 'image'
  #       required: false
  #     - label: 'Description en français'
  #       name: 'description'
  #       widget: 'markdown'
  #       required: false
  #     - label: 'Description en anglais'
  #       name: 'description_en'
  #       widget: 'markdown'
  #       required: false
  - name: "awards"
    create: true  
    label: "Awards"
    files:
      - file: "docs/_data/awards.yml"
        label: "Awards List"
        name: "awards_list"
        fields:
          - label: "Awards"
            name: ""
            widget: "list"
            fields:
              - label: "Name"
                name: "name"
                widget: "object"
                fields:
                  - { label: "English", name: "en", widget: "string" }
                  - { label: "French", name: "fr", widget: "string" }

              - label: "Media"
                name: "media"
                widget: "object"
                fields:
                  - { label: "Image", name: "path", widget: "image" }

                  - label: "Alt Text"
                    name: "alt"
                    widget: "object"
                    fields:
                      - { label: "English", name: "en", widget: "string" }
                      - { label: "French", name: "fr", widget: "string" }
